# Generated by Django 5.0.7 on 2024-09-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='map_svg',
            field=models.TextField(),
        ),
    ]
