version: "3.8"

services:
  # Django Service
  app:
    restart: always
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: >
      sh -c "
      python manage.py migrate && 
      python manage.py loaddata mock_data.json &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
